import Head from "next/head";
import Image from "next/image";
import {
  AppBar,
  Box,
  CssBaseline,
  Toolbar,
  Container,
  useMediaQuery,
  Grid,
  Typography,
} from "@mui/material";
import { styled, useTheme } from "@mui/material/styles";

import styles from "../styles/Home.module.css";
import Header from "./components/Home/Header";
import Counters from "./components/Home/counters";
import CuroselCard from "./components/Home/curoselCard";
import CollapseCard from "./components/Home/collapseCard";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello from BIO-DIVERSITY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar enableColorOnDark position="fixed" color="inherit" elevation={0}>
        <Toolbar>
          <Header />
        </Toolbar>
      </AppBar>

      <div className={styles.main}>
        <Box
          component="section"
          style={{
            border: "1px solid #e7e7e7",
            borderRadius: 20,
            padding: 30,
            width: "60%",
          }}
        >
          <Grid container item xs={12} sx={{ mx: "auto" }}>
            <Grid item xs={8}>
              <Typography  gutterBottom variant="h1" component='div'>
                Listing the World’s BIO Diversity
              </Typography>
              <Typography gutterBottom variant="h5" component='div'>
                BIO-D is a global algal database of taxonomic, nomenclatural and
                distributional information.
              </Typography>
              <CuroselCard />
              <Counters />

              {/* <h1 className={styles.title}>Getting started BIO-DIVERSITY!</h1> */}
            </Grid>
            <Grid item xs={4}>
            <Typography gutterBottom variant="h2" component='div'>
              Latest Additions
              </Typography>
              <CollapseCard />
              {/* <h1 className={styles.title}>Getting started BIO-DIVERSITY!</h1> */}
            </Grid>
          </Grid>
        </Box>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>H-Tech</span>
        </a>
      </footer>
    </div>
  );
}
