import * as React from 'react';
import Head from "next/head";
import Image from "next/image";
import {
  AppBar,
  Box,
  CssBaseline,
  Toolbar,
  Container,
  useMediaQuery,
  Grid,
  Typography,
  Divider,
  TextField,
  Button,
  FormControl,
  IconButton,
  InputBase,
  Paper,
  Input,
  OutlinedInput,
} from "@mui/material";
import { styled, useTheme } from "@mui/material/styles";
import SearchIcon from "@mui/icons-material/Search";

import styles from "../styles/Home.module.css";
import Header from "./components/Home/Header";
import Counters from "./components/Home/counters";
import CuroselCard from "./components/Home/curoselCard";
import CollapseCard from "./components/Home/collapseCard";
import Footer from "./components/Home/Footer/Footer";
const img = require("../pages/assets/images/species3.jpg");
import { Icon } from "@iconify/react";
import { height, width } from "@mui/system";

export default function Home() {
  const [spacing, setSpacing] = React.useState(2);

  const handleChange = (event) => {
    setSpacing(Number(event.target.value));
  };

  const jsx = `
<Grid container spacing={${spacing}}>
`;

  return (
    <div className={styles.body}>
      {/* <Head>
        <title>Hello from BIO-DIVERSITY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <div className={styles.main}>
        <Box component="section" className={styles.main_page}>
          <Grid container item xs={12} md={12} sx={{ mx: "auto" }}>
            <Grid
              item
              xs={12}
              md={12}
              // style={{ borderRadius: "20px", paddingRight: "10px" }}
            >
              <Grid className={styles.featuredContainer}>
                <Header index={0} />

                <Grid
                  className={styles.container}
                  container
                  spacing={0}
                  direction="column"
                  alignItems="center"
                  justifyContent="center"
                  // style={{ minHeight: "50vh" }}
                >
                  <Grid>
                    <Typography className={styles.font}>
                      Listing the World’s BIO Diversity
                    </Typography>{" "}
                    <Counters />
                  </Grid>
                  <Grid
                    className={styles.searchField}
                    component="form"
                    sx={{
                      // p: "2px 4px",
                      display: "flex",
                      alignItems: "center",
                      // width: 400,
                      height: 55,
                      // pr: "25px",
                    }}
                  >
                    <FormControl sx={{ width: "25ch" }}    className={styles.search}>
                      <OutlinedInput placeholder="Please enter text" />
                    </FormControl>
                    <Button
                      type="button"
                      sx={{ p: "13px" }}
                      aria-label="search"
                      style={{
                        color: "white",
                        borderRadius: 0,
                        fontWeight: 600,
                        backgroundColor: "#c44d34",
                        width: "140px",
                      }}
                    >
                      <SearchIcon /> Search
                    </Button>

                    {/* <IconButton color="primary" sx={{ p: '10px' }} aria-label="directions">
        <DirectionsIcon />
      </IconButton> */}
                  </Grid>
                  
                </Grid>
              </Grid>

              {/* <h1 className={styles.title}>Getting started BIO-DIVERSITY!</h1> */}
            </Grid>
       
          </Grid>
           <Grid className={styles.secondContainer}>
            

          <Grid className="col-md-12">
					   <h3 role="heading" aria-level="2" id="recent-sightings">Recent sightings</h3>
				   </Grid>
           
           <Grid sx={{ flexGrow: 1 }} container spacing={1}>
      <Grid item xs={12}>
        <Grid container justifyContent="center" spacing={spacing}>
          {[0, 1, 2].map((value) => (
            <Grid key={value} item>
              <Paper
                sx={{
                  height: 200,
                  width: 200,
                  backgroundColor: (theme) =>
                    theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
                }}
              />
            </Grid>
          ))}
        </Grid>
      </Grid>
      {/* <Grid item xs={12}>

      </Grid> */}
    </Grid>
       </Grid>
        </Box>
      </div>

      <Footer />
    </div>
  );
}
