name: bio_deploy

on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Connect_to_server
        uses: MitchWind/ftp-deploy@master
        with:
            server: 66.29.151.71
            username: bio
            password: /bio-diversity/
            node-version: 16.13.1
        
      - run: yarn install
      - run: yarn dev --if-present