name: bio_deploy

on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Connect_to_server
        uses: SamKirkland/FTP-Deploy-Action@3.1.2
        with:
            ftp-server: ftp://66.29.151.71
            ftp-username: bio
            ftp-password: bio_diversity
            local-dir: /home/bio/bio-diversity/
        
      - run: yarn install
      - run: yarn dev --if-present