name: bio-deploy

on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout & Deploy
        uses: actions/checkout@main
      - run: yarn install
      - run: yarn build
      - run: yarn preDeploy
      - name: Ftp Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
            server: ftp://66.29.151.71
            username: bio
            password: bio_diversity
            local-dir: ./out/
            server-dir: /home/bio/bio-diversity/out/
      - run: yarn add node-fetch@2
      - run: node server/deploy.js