name: bio_deploy

on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout & Deploy
        uses: actions/checkout@main
      - run: npm install node-fetch@2
      - run: node server/deploy.js