name: bio_deploy

on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout & Deploy
        uses: actions/checkout@main
      - name: Ftp Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
            server: 66.29.151.71
            username: bio
            password: bio_diversity
            server-dir: /home/bio/bio-diversity/
            
      # - run: yarn add node-fetch@2
      # - run: node server/deploy.js