name: bio-deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout & Deploy
        uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - name: Ftp Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
            server: www.biodiversitybangladesh.du.ac.bd
            username: bio
            password: bio_diversity
            local-dir: ./out/
            server-dir: /home/bio/bio-diversity/out/
      - run: yarn add node-fetch@2
      - run: node server/deploy.js